#!/bin/sh

DIR=$(dirname $0)

DB_SEARCH_PATH="/opt/tmp/wikipedia"
WIKIDUMP_STATIC_DATA="$DIR/../data"
WIKIDUMP_SERVER="$DIR/../src/bin/wikidump_server"

if [ ! -x "$WIKIDUMP_SERVER" ] ; then
   echo "wikidump_server not found. Abort"
   exit 1
fi

WIKIDUMP_SQLITE_DB=""
n=0
for i in $(find $DB_SEARCH_PATH -maxdepth 1 -name "*.sqlite" ) ; do
   #test -f "$i-journal" && continue
   if [ -z "$WIKIDUMP_SQLITE_DB" ] ; then
      WIKIDUMP_SQLITE_DB="$i"
   else
      WIKIDUMP_SQLITE_DB="$WIKIDUMP_SQLITE_DB:$i"
   fi
   n=$(($n + 1))
   if [ $n -eq 9 ] ; then
      break;
   fi
done
if [ -z "$WIKIDUMP_SQLITE_DB" ] ; then
   echo "No wikidump DB found. Aboort"
   exit 2
fi

export WIKIDUMP_SQLITE_DB
export WIKIDUMP_STATIC_DATA

RUN_IN=""
while [ "$1" ] ; do
   case "$1" in
      -v|v)
         RUN_IN="valgrind --log-fd=2 --leak-check=full --show-reachable=yes --track-origins=yes"
         ;;
      -c|c)
         RUN_IN="valgrind --tool=callgrind --callgrind-out-file=/tmp/ws.out"
         ;;
      -g|g)
         RUN_IN="gdb"
         ;;
      -nl|nl)
         export WIKIDUMP_NO_PAGE_EXISTS=1
         ;;
      -ni|ni)
         export WIKIDUMP_NO_IMAGE=1
         ;;
      -d|d)
         export WIKI_DEBUG=1
         ;;
      h|-h|--h|-help|--help)
         echo "Usage: $(basename $0) [[-]v|g|nl|d|h]

	-h  this message	
	-v  run in valgrind --tool=memcheck
	-c  run in valgrind --tool=callgrind
	-g  run in gdb
	-d  show debug messages
	-nl don't check if page exists for links
	-ni use 404.png for all image
"
         exit 0
         ;;
   esac
   shift
done

$RUN_IN $WIKIDUMP_SERVER
