/* Lang list converted from wikimedia Names.php */
#include <Eina.h>
#include <stdlib.h>

#include "wiki_lang.h"

static const Wiki_Lang wiki_languages[] = {
   {"aa", "", "ltr", "Qafár af", NULL, NULL},
   {"ab", "", "ltr", "Аҧсуа", NULL, NULL},
   {"ace", "", "ltr", "Acèh", NULL, NULL},
   {"af", "", "ltr", "Afrikaans", NULL, NULL},
   {"ak", "", "ltr", "Akan", NULL, NULL},
   {"aln", "", "ltr", "Gegë", NULL, NULL},
   {"als", "", "ltr", "Alemannisch", NULL, NULL},
   {"am", "", "ltr", "አማርኛ", NULL, NULL},
   {"an", "", "ltr", "Aragonés", NULL, NULL},
   {"ang", "", "ltr", "Ænglisc", NULL, NULL},
   {"ar", "", "rtl", "العربية", NULL, NULL},
   {"arc", "", "rtl", "ܐܪܡܝܐ", NULL, NULL},
   {"arn", "", "ltr", "Mapudungun", NULL, NULL},
   {"ary", "", "ltr", "Maġribi", NULL, NULL},
   {"arz", "", "ltr", "مصرى", NULL, NULL},
   {"as", "", "ltr", "অসমীয়া", NULL, NULL},
   {"ast", "", "ltr", "Asturianu", NULL, NULL},
   {"av", "", "ltr", "Авар", NULL, NULL},
   {"avk", "", "ltr", "Kotava", NULL, NULL},
   {"ay", "", "ltr", "Aymar aru", NULL, NULL},
   {"az", "", "ltr", "Azərbaycanca", NULL, NULL},
   {"ba", "", "ltr", "Башҡортса", NULL, NULL},
   {"bar", "", "ltr", "Boarisch", NULL, NULL},
   {"bat-smg", "", "ltr", "Žemaitėška", NULL, NULL},
   {"bcc", "", "ltr", "بلوچی مکرانی", NULL, NULL},
   {"bcl", "", "ltr", "Bikol Central", NULL, NULL},
   {"be", "", "ltr", "Беларуская", NULL, NULL},
   {"be-tarask", "", "ltr", "‪Беларуская (тарашкевіца)‬", NULL, NULL},
   {"be-x-old", "", "ltr", "‪Беларуская (тарашкевіца)‬", NULL, NULL},
   {"bg", "", "ltr", "Български", NULL, NULL},
   {"bh", "", "ltr", "भोजपुरी", NULL, NULL},
   {"bi", "", "ltr", "Bislama", NULL, NULL},
   {"bjn", "", "ltr", "Bahasa Banjar", NULL, NULL},
   {"bm", "", "ltr", "Bamanankan", NULL, NULL},
   {"bn", "", "ltr", "বাংলা", NULL, NULL},
   {"bo", "", "ltr", "བོད་ཡིག", NULL, NULL},
   {"bpy", "", "ltr", "ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী", NULL, NULL},
   {"bqi", "", "ltr", "بختياري", NULL, NULL},
   {"br", "", "ltr", "Brezhoneg", NULL, NULL},
   {"bs", "", "ltr", "Bosanski", NULL, NULL},
   {"bug", "", "ltr", "ᨅᨔ ᨕᨘᨁᨗ", NULL, NULL},
   {"bxr", "", "ltr", "Буряад", NULL, NULL},
   {"ca", "", "ltr", "Català", NULL, NULL},
   {"cbk-zam", "", "ltr", "Chavacano de Zamboanga", NULL, NULL},
   {"cdo", "", "ltr", "Mìng-dĕ̤ng-ngṳ̄", NULL, NULL},
   {"ce", "", "ltr", "Нохчийн", NULL, NULL},
   {"ceb", "", "ltr", "Cebuano", NULL, NULL},
   {"ch", "", "ltr", "Chamoru", NULL, NULL},
   {"cho", "", "ltr", "Choctaw", NULL, NULL},
   {"chr", "", "ltr", "ᏣᎳᎩ", NULL, NULL},
   {"chy", "", "ltr", "Tsetsêhestâhese", NULL, NULL},
   {"ckb", "", "ltr", "کوردی", NULL, NULL},
   {"co", "", "ltr", "Corsu", NULL, NULL},
   {"cps", "", "ltr", "Capiceño", NULL, NULL},
   {"cr", "", "ltr", "Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ", NULL, NULL},
   {"crh", "", "ltr", "Qırımtatarca", NULL, NULL},
   {"crh-latn", "", "ltr", "‪Qırımtatarca (Latin)‬", NULL, NULL},
   {"crh-cyrl", "", "ltr", "‪Къырымтатарджа (Кирилл)‬", NULL, NULL},
   {"cs", "", "ltr", "Česky", NULL, NULL},
   {"csb", "", "ltr", "Kaszëbsczi", NULL, NULL},
   {"cu", "", "ltr", "Словѣ́ньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ", NULL, NULL},
   {"cv", "", "ltr", "Чӑвашла", NULL, NULL},
   {"cy", "", "ltr", "Cymraeg", NULL, NULL},
   {"da", "", "ltr", "Dansk", NULL, NULL},
   {"de", "", "ltr", "Deutsch", NULL, NULL},
   {"de-at", "", "ltr", "Österreichisches Deutsch", NULL, NULL},
   {"de-ch", "", "ltr", "Schweizer Hochdeutsch", NULL, NULL},
   {"de-formal", "", "ltr", "‪Deutsch (Sie-Form)‬", NULL, NULL},
   {"diq", "", "ltr", "Zazaki", NULL, NULL},
   {"dsb", "", "ltr", "Dolnoserbski", NULL, NULL},
   {"dv", "", "rtl", "ދިވެހިބަސް", NULL, NULL},
   {"dz", "", "ltr", "ཇོང་ཁ", NULL, NULL},
   {"ee", "", "ltr", "Eʋegbe", NULL, NULL},
   {"el", "", "ltr", "Ελληνικά", NULL, NULL},
   {"eml", "", "ltr", "Emiliàn e rumagnòl", NULL, NULL},
   {"en", "", "ltr", "English", NULL, NULL},
   {"en-gb", "", "ltr", "British English", NULL, NULL},
   {"eo", "", "ltr", "Esperanto", NULL, NULL},
   {"es", "", "ltr", "Español", NULL, NULL},
   {"et", "", "ltr", "Eesti", NULL, NULL},
   {"eu", "", "ltr", "Euskara", NULL, NULL},
   {"ext", "", "ltr", "Estremeñu", NULL, NULL},
   {"fa", "", "rtl", "فارسی", NULL, NULL},
   {"ff", "", "ltr", "Fulfulde", NULL, NULL},
   {"fi", "", "ltr", "Suomi", NULL, NULL},
   {"fiu-vro", "", "ltr", "Võro", NULL, NULL},
   {"fj", "", "ltr", "Na Vosa Vakaviti", NULL, NULL},
   {"fo", "", "ltr", "Føroyskt", NULL, NULL},
   {"fr", "", "ltr", "Français", NULL, NULL},
   {"frc", "", "ltr", "Français cadien", NULL, NULL},
   {"frp", "", "ltr", "Arpetan", NULL, NULL},
   {"frr", "", "ltr", "Nordfriisk", NULL, NULL},
   {"fur", "", "ltr", "Furlan", NULL, NULL},
   {"fy", "", "ltr", "Frysk", NULL, NULL},
   {"ga", "", "ltr", "Gaeilge", NULL, NULL},
   {"gag", "", "ltr", "Gagauz", NULL, NULL},
   {"gan", "", "ltr", "贛語", NULL, NULL},
   {"gan-hans", "", "ltr", "‪赣语(简体)‬", NULL, NULL},
   {"gan-hant", "", "ltr", "‪贛語(繁體)‬", NULL, NULL},
   {"gd", "", "ltr", "Gàidhlig", NULL, NULL},
   {"gl", "", "ltr", "Galego", NULL, NULL},
   {"glk", "", "rtl", "گیلکی", NULL, NULL},
   {"gn", "", "ltr", "Avañe'ẽ", NULL, NULL},
   {"got", "", "ltr", "𐌲𐌿𐍄𐌹𐍃𐌺", NULL, NULL},
   {"grc", "", "ltr", "Ἀρχαία ἑλληνικὴ", NULL, NULL},
   {"gsw", "", "ltr", "Alemannisch", NULL, NULL},
   {"gu", "", "ltr", "ગુજરાતી", NULL, NULL},
   {"gv", "", "ltr", "Gaelg", NULL, NULL},
   {"ha", "", "rtl", "هَوُسَ", NULL, NULL},
   {"hak", "", "ltr", "Hak-kâ-fa", NULL, NULL},
   {"haw", "", "ltr", "Hawai`i", NULL, NULL},
   {"he", "", "rtl", "עברית", NULL, NULL},
   {"hi", "", "ltr", "हिन्दी", NULL, NULL},
   {"hif", "", "ltr", "Fiji Hindi", NULL, NULL},
   {"hif-latn", "", "ltr", "Fiji Hindi", NULL, NULL},
   {"hil", "", "ltr", "Ilonggo", NULL, NULL},
   {"ho", "", "ltr", "Hiri Motu", NULL, NULL},
   {"hr", "", "ltr", "Hrvatski", NULL, NULL},
   {"hsb", "", "ltr", "Hornjoserbsce", NULL, NULL},
   {"ht", "", "ltr", "Kreyòl ayisyen", NULL, NULL},
   {"hu", "", "ltr", "Magyar", NULL, NULL},
   {"hy", "", "ltr", "Հայերեն", NULL, NULL},
   {"hz", "", "ltr", "Otsiherero", NULL, NULL},
   {"ia", "", "ltr", "Interlingua", NULL, NULL},
   {"id", "", "ltr", "Bahasa Indonesia", NULL, NULL},
   {"ie", "", "ltr", "Interlingue", NULL, NULL},
   {"ig", "", "ltr", "Igbo", NULL, NULL},
   {"ii", "", "ltr", "ꆇꉙ", NULL, NULL},
   {"ik", "", "ltr", "Iñupiak", NULL, NULL},
   {"ike-cans", "", "ltr", "ᐃᓄᒃᑎᑐᑦ", NULL, NULL},
   {"ike-latn", "", "ltr", "inuktitut", NULL, NULL},
   {"ilo", "", "ltr", "Ilokano", NULL, NULL},
   {"inh", "", "ltr", "ГІалгІай Ğalğaj", NULL, NULL},
   {"io", "", "ltr", "Ido", NULL, NULL},
   {"is", "", "ltr", "Íslenska", NULL, NULL},
   {"it", "", "ltr", "Italiano", NULL, NULL},
   {"iu", "", "ltr", "ᐃᓄᒃᑎᑐᑦ/inuktitut", NULL, NULL},
   {"ja", "", "ltr", "日本語", NULL, NULL},
   {"jbo", "", "ltr", "Lojban", NULL, NULL},
   {"jut", "", "ltr", "Jysk", NULL, NULL},
   {"jv", "", "ltr", "Basa Jawa", NULL, NULL},
   {"ka", "", "ltr", "ქართული", NULL, NULL},
   {"kaa", "", "ltr", "Qaraqalpaqsha", NULL, NULL},
   {"kab", "", "ltr", "Taqbaylit", NULL, NULL},
   {"kbd", "", "ltr", "Къэбэрдеибзэ / Qabardjajəbza", NULL, NULL},
   {"kbd-cyrl", "", "ltr", "къэбэрдеибзэ", NULL, NULL},
   {"kg", "", "ltr", "Kongo", NULL, NULL},
   {"ki", "", "ltr", "Gĩkũyũ", NULL, NULL},
   {"kiu", "", "ltr", "Kırmancki", NULL, NULL},
   {"kj", "", "ltr", "Kwanyama", NULL, NULL},
   {"kk", "", "ltr", "Қазақша", NULL, NULL},
   {"kk-arab", "", "ltr", "‫قازاقشا (تٴوتە)‬", NULL, NULL},
   {"kk-cyrl", "", "ltr", "‪Қазақша (кирил)‬", NULL, NULL},
   {"kk-latn", "", "ltr", "‪Qazaqşa (latın)‬", NULL, NULL},
   {"kk-cn", "", "ltr", "‫قازاقشا (جۇنگو)‬", NULL, NULL},
   {"kk-kz", "", "ltr", "‪Қазақша (Қазақстан)‬", NULL, NULL},
   {"kk-tr", "", "ltr", "‪Qazaqşa (Türkïya)‬", NULL, NULL},
   {"kl", "", "ltr", "Kalaallisut", NULL, NULL},
   {"km", "", "ltr", "ភាសាខ្មែរ", NULL, NULL},
   {"kn", "", "ltr", "ಕನ್ನಡ", NULL, NULL},
   {"ko", "", "ltr", "한국어", NULL, NULL},
   {"ko-kp", "", "ltr", "한국어 (조선)", NULL, NULL},
   {"koi", "", "ltr", "Перем Коми", NULL, NULL},
   {"kr", "", "ltr", "Kanuri", NULL, NULL},
   {"krc", "", "ltr", "Къарачай-Малкъар", NULL, NULL},
   {"kri", "", "ltr", "Krio", NULL, NULL},
   {"krj", "", "ltr", "Kinaray-a", NULL, NULL},
   {"ks", "", "rtl", "कश्मीरी - (كشميري)", NULL, NULL},
   {"ksh", "", "ltr", "Ripoarisch", NULL, NULL},
   {"ku", "", "rtl", "Kurdî", NULL, NULL},
   {"ku-latn", "", "ltr", "‪Kurdî (latînî)‬", NULL, NULL},
   {"ku-arab", "", "ltr", "‫كوردي (عەرەبی)‬", NULL, NULL},
   {"kv", "", "ltr", "Коми", NULL, NULL},
   {"kw", "", "ltr", "Kernowek", NULL, NULL},
   {"ky", "", "ltr", "Кыргызча", NULL, NULL},
   {"la", "", "ltr", "Latina", NULL, NULL},
   {"lad", "", "ltr", "Ladino", NULL, NULL},
   {"lb", "", "ltr", "Lëtzebuergesch", NULL, NULL},
   {"lbe", "", "ltr", "Лакку", NULL, NULL},
   {"lez", "", "ltr", "Лезги", NULL, NULL},
   {"lfn", "", "ltr", "Lingua Franca Nova", NULL, NULL},
   {"lg", "", "ltr", "Luganda", NULL, NULL},
   {"li", "", "ltr", "Limburgs", NULL, NULL},
   {"lij", "", "ltr", "Líguru", NULL, NULL},
   {"lmo", "", "ltr", "Lumbaart", NULL, NULL},
   {"ln", "", "ltr", "Lingála", NULL, NULL},
   {"lo", "", "ltr", "ລາວ", NULL, NULL},
   {"loz", "", "ltr", "Silozi", NULL, NULL},
   {"lt", "", "ltr", "Lietuvių", NULL, NULL},
   {"ltg", "", "ltr", "Latgaļu", NULL, NULL},
   {"lv", "", "ltr", "Latviešu", NULL, NULL},
   {"lzh", "", "ltr", "文言", NULL, NULL},
   {"lzz", "", "ltr", "Lazuri", NULL, NULL},
   {"mai", "", "ltr", "मैथिली", NULL, NULL},
   {"map-bms", "", "ltr", "Basa Banyumasan", NULL, NULL},
   {"mdf", "", "ltr", "Мокшень", NULL, NULL},
   {"mg", "", "ltr", "Malagasy", NULL, NULL},
   {"mh", "", "ltr", "Ebon", NULL, NULL},
   {"mhr", "", "ltr", "Олык Марий", NULL, NULL},
   {"mi", "", "ltr", "Māori", NULL, NULL},
   {"min", "", "ltr", "Baso Minangkabau", NULL, NULL},
   {"mk", "", "ltr", "Македонски", NULL, NULL},
   {"ml", "", "ltr", "മലയാളം", NULL, NULL},
   {"mn", "", "ltr", "Монгол", NULL, NULL},
   {"mo", "", "ltr", "Молдовеняскэ", NULL, NULL},
   {"mr", "", "ltr", "मराठी", NULL, NULL},
   {"mrj", "", "ltr", "Кырык мары", NULL, NULL},
   {"ms", "", "ltr", "Bahasa Melayu", NULL, NULL},
   {"mt", "", "ltr", "Malti", NULL, NULL},
   {"mus", "", "ltr", "Mvskoke", NULL, NULL},
   {"mwl", "", "ltr", "Mirandés", NULL, NULL},
   {"my", "", "ltr", "မြန်မာဘာသာ", NULL, NULL},
   {"myv", "", "ltr", "Эрзянь", NULL, NULL},
   {"mzn", "", "rtl", "مازِرونی", NULL, NULL},
   {"na", "", "ltr", "Dorerin Naoero", NULL, NULL},
   {"nah", "", "ltr", "Nāhuatl", NULL, NULL},
   {"nan", "", "ltr", "Bân-lâm-gú", NULL, NULL},
   {"nap", "", "ltr", "Nnapulitano", NULL, NULL},
   {"nb", "", "ltr", "‪Norsk (bokmål)‬", NULL, NULL},
   {"nds", "", "ltr", "Plattdüütsch", NULL, NULL},
   {"nds-nl", "", "ltr", "Nedersaksisch", NULL, NULL},
   {"ne", "", "ltr", "नेपाली", NULL, NULL},
   {"new", "", "ltr", "नेपाल भाषा", NULL, NULL},
   {"ng", "", "ltr", "Oshiwambo", NULL, NULL},
   {"niu", "", "ltr", "Niuē", NULL, NULL},
   {"nl", "", "ltr", "Nederlands", NULL, NULL},
   {"nl-informal", "", "ltr", "‪Nederlands (informeel)‬", NULL, NULL},
   {"nn", "", "ltr", "‪Norsk (nynorsk)‬", NULL, NULL},
   {"no", "", "ltr", "‪Norsk (bokmål)‬", NULL, NULL},
   {"nov", "", "ltr", "Novial", NULL, NULL},
   {"nrm", "", "ltr", "Nouormand", NULL, NULL},
   {"nso", "", "ltr", "Sesotho sa Leboa", NULL, NULL},
   {"nv", "", "ltr", "Diné bizaad", NULL, NULL},
   {"ny", "", "ltr", "Chi-Chewa", NULL, NULL},
   {"oc", "", "ltr", "Occitan", NULL, NULL},
   {"om", "", "ltr", "Oromoo", NULL, NULL},
   {"or", "", "ltr", "ଓଡ଼ିଆ", NULL, NULL},
   {"os", "", "ltr", "Иронау", NULL, NULL},
   {"pa", "", "ltr", "ਪੰਜਾਬੀ", NULL, NULL},
   {"pag", "", "ltr", "Pangasinan", NULL, NULL},
   {"pam", "", "ltr", "Kapampangan", NULL, NULL},
   {"pap", "", "ltr", "Papiamentu", NULL, NULL},
   {"pcd", "", "ltr", "Picard", NULL, NULL},
   {"pdc", "", "ltr", "Deitsch", NULL, NULL},
   {"pdt", "", "ltr", "Plautdietsch", NULL, NULL},
   {"pfl", "", "ltr", "Pälzisch", NULL, NULL},
   {"pi", "", "ltr", "पािऴ", NULL, NULL},
   {"pih", "", "ltr", "Norfuk / Pitkern", NULL, NULL},
   {"pl", "", "ltr", "Polski", NULL, NULL},
   {"pms", "", "ltr", "Piemontèis", NULL, NULL},
   {"pnb", "", "ltr", "پنجابی", NULL, NULL},
   {"pnt", "", "ltr", "Ποντιακά", NULL, NULL},
   {"prg", "", "ltr", "Prūsiskan", NULL, NULL},
   {"ps", "", "rtl", "پښتو", NULL, NULL},
   {"pt", "", "ltr", "Português", NULL, NULL},
   {"pt-br", "", "ltr", "Português do Brasil", NULL, NULL},
   {"qu", "", "ltr", "Runa Simi", NULL, NULL},
   {"rgn", "", "ltr", "Rumagnôl", NULL, NULL},
   {"rif", "", "ltr", "Tarifit", NULL, NULL},
   {"rm", "", "ltr", "Rumantsch", NULL, NULL},
   {"rmy", "", "ltr", "Romani", NULL, NULL},
   {"rn", "", "ltr", "Kirundi", NULL, NULL},
   {"ro", "", "ltr", "Română", NULL, NULL},
   {"roa-rup", "", "ltr", "Armãneashce", NULL, NULL},
   {"roa-tara", "", "ltr", "Tarandíne", NULL, NULL},
   {"ru", "", "ltr", "Русский", NULL, NULL},
   {"rue", "", "ltr", "Русиньскый", NULL, NULL},
   {"ruq", "", "ltr", "Vlăheşte", NULL, NULL},
   {"ruq-cyrl", "", "ltr", "Влахесте", NULL, NULL},
   {"ruq-latn", "", "ltr", "Vlăheşte", NULL, NULL},
   {"rw", "", "ltr", "Kinyarwanda", NULL, NULL},
   {"sa", "", "ltr", "संस्कृत", NULL, NULL},
   {"sah", "", "ltr", "Саха тыла", NULL, NULL},
   {"sc", "", "ltr", "Sardu", NULL, NULL},
   {"scn", "", "ltr", "Sicilianu", NULL, NULL},
   {"sco", "", "ltr", "Scots", NULL, NULL},
   {"sd", "", "rtl", "سنڌي", NULL, NULL},
   {"sdc", "", "ltr", "Sassaresu", NULL, NULL},
   {"se", "", "ltr", "Sámegiella", NULL, NULL},
   {"sei", "", "ltr", "Cmique Itom", NULL, NULL},
   {"sg", "", "ltr", "Sängö", NULL, NULL},
   {"sgs", "", "ltr", "Žemaitėška", NULL, NULL},
   {"sh", "", "ltr", "Srpskohrvatski / Српскохрватски", NULL, NULL},
   {"shi", "", "ltr", "Tašlḥiyt", NULL, NULL},
   {"si", "", "ltr", "සිංහල", NULL, NULL},
   {"simple", "", "ltr", "Simple English", NULL, NULL},
   {"sk", "", "ltr", "Slovenčina", NULL, NULL},
   {"sl", "", "ltr", "Slovenščina", NULL, NULL},
   {"sli", "", "ltr", "Schläsch", NULL, NULL},
   {"sm", "", "ltr", "Gagana Samoa", NULL, NULL},
   {"sma", "", "ltr", "Åarjelsaemien", NULL, NULL},
   {"sn", "", "ltr", "chiShona", NULL, NULL},
   {"so", "", "ltr", "Soomaaliga", NULL, NULL},
   {"sq", "", "ltr", "Shqip", NULL, NULL},
   {"sr", "", "ltr", "Српски / Srpski", NULL, NULL},
   {"sr-ec", "", "ltr", "‪Српски (ћирилица)‬", NULL, NULL},
   {"sr-el", "", "ltr", "‪Srpski (latinica)‬", NULL, NULL},
   {"srn", "", "ltr", "Sranantongo", NULL, NULL},
   {"ss", "", "ltr", "SiSwati", NULL, NULL},
   {"st", "", "ltr", "Sesotho", NULL, NULL},
   {"stq", "", "ltr", "Seeltersk", NULL, NULL},
   {"su", "", "ltr", "Basa Sunda", NULL, NULL},
   {"sv", "", "ltr", "Svenska", NULL, NULL},
   {"sw", "", "ltr", "Kiswahili", NULL, NULL},
   {"szl", "", "ltr", "Ślůnski", NULL, NULL},
   {"ta", "", "ltr", "தமிழ்", NULL, NULL},
   {"tcy", "", "ltr", "ತುಳು", NULL, NULL},
   {"te", "", "ltr", "తెలుగు", NULL, NULL},
   {"tet", "", "ltr", "Tetun", NULL, NULL},
   {"tg", "", "ltr", "Тоҷикӣ", NULL, NULL},
   {"tg-cyrl", "", "ltr", "Тоҷикӣ", NULL, NULL},
   {"tg-latn", "", "ltr", "tojikī", NULL, NULL},
   {"th", "", "ltr", "ไทย", NULL, NULL},
   {"ti", "", "ltr", "ትግርኛ", NULL, NULL},
   {"tk", "", "ltr", "Türkmençe", NULL, NULL},
   {"tl", "", "ltr", "Tagalog", NULL, NULL},
   {"tn", "", "ltr", "Setswana", NULL, NULL},
   {"to", "", "ltr", "lea faka-Tonga", NULL, NULL},
   {"tokipona", "", "ltr", "Toki Pona", NULL, NULL},
   {"tp", "", "ltr", "Toki Pona (deprecated:tokipona)", NULL, NULL},
   {"tpi", "", "ltr", "Tok Pisin", NULL, NULL},
   {"tr", "", "ltr", "Türkçe", NULL, NULL},
   {"ts", "", "ltr", "Xitsonga", NULL, NULL},
   {"tt", "", "ltr", "Татарча/Tatarça", NULL, NULL},
   {"tt-cyrl", "", "ltr", "Татарча", NULL, NULL},
   {"tt-latn", "", "ltr", "Tatarça", NULL, NULL},
   {"tum", "", "ltr", "chiTumbuka", NULL, NULL},
   {"tw", "", "ltr", "Twi", NULL, NULL},
   {"ty", "", "ltr", "Reo Mā`ohi", NULL, NULL},
   {"tyv", "", "ltr", "Тыва дыл", NULL, NULL},
   {"udm", "", "ltr", "Удмурт", NULL, NULL},
   {"ug", "", "ltr", "ئۇيغۇرچە / Uyghurche‎", NULL, NULL},
   {"ug-arab", "", "ltr", "ئۇيغۇرچە", NULL, NULL},
   {"ug-latn", "", "ltr", "Uyghurche‎", NULL, NULL},
   {"uk", "", "ltr", "Українська", NULL, NULL},
   {"ur", "", "rtl", "اردو", NULL, NULL},
   {"uz", "", "ltr", "O'zbek", NULL, NULL},
   {"ve", "", "ltr", "Tshivenda", NULL, NULL},
   {"vec", "", "ltr", "Vèneto", NULL, NULL},
   {"vep", "", "ltr", "Vepsan kel'", NULL, NULL},
   {"vi", "", "ltr", "Tiếng Việt", NULL, NULL},
   {"vls", "", "ltr", "West-Vlams", NULL, NULL},
   {"vmf", "", "ltr", "Mainfränkisch", NULL, NULL},
   {"vo", "", "ltr", "Volapük", NULL, NULL},
   {"vot", "", "ltr", "Vaďďa", NULL, NULL},
   {"vro", "", "ltr", "Võro", NULL, NULL},
   {"wa", "", "ltr", "Walon", NULL, NULL},
   {"war", "", "ltr", "Winaray", NULL, NULL},
   {"wo", "", "ltr", "Wolof", NULL, NULL},
   {"wuu", "", "ltr", "吴语", NULL, NULL},
   {"xal", "", "ltr", "Хальмг", NULL, NULL},
   {"xh", "", "ltr", "isiXhosa", NULL, NULL},
   {"xmf", "", "ltr", "მარგალური", NULL, NULL},
   {"yi", "", "rtl", "ייִדיש", NULL, NULL},
   {"yo", "", "ltr", "Yorùbá", NULL, NULL},
   {"yue", "", "ltr", "粵語", NULL, NULL},
   {"za", "", "ltr", "Vahcuengh", NULL, NULL},
   {"zea", "", "ltr", "Zeêuws", NULL, NULL},
   {"zh", "", "ltr", "中文", NULL, NULL},
   {"zh-classical", "", "ltr", "文言", NULL, NULL},
   {"zh-cn", "", "ltr", "‪中文(中国大陆)‬", NULL, NULL},
   {"zh-hans", "", "ltr", "‪中文(简体)‬", NULL, NULL},
   {"zh-hant", "", "ltr", "‪中文(繁體)‬", NULL, NULL},
   {"zh-hk", "", "ltr", "‪中文(香港)‬", NULL, NULL},
   {"zh-min-nan", "", "ltr", "Bân-lâm-gú", NULL, NULL},
   {"zh-mo", "", "ltr", "‪中文(澳門)‬", NULL, NULL},
   {"zh-my", "", "ltr", "‪中文(马来西亚)‬", NULL, NULL},
   {"zh-sg", "", "ltr", "‪中文(新加坡)‬", NULL, NULL},
   {"zh-tw", "", "ltr", "‪中文(台灣)‬", NULL, NULL},
   {"zh-yue", "", "ltr", "粵語", NULL, NULL},
   {"zu", "", "ltr", "isiZulu", NULL, NULL},
   {NULL, NULL, NULL, NULL, NULL, NULL}
};

const char *wiki_lang_magic_word_get(Eina_Hash *hash, const char *lang, const char *word)
{
   const Wiki_Lang *wl = NULL;
   const char *ret = NULL;

   if(! hash) return ret;
   if(! lang) return ret;
   if(! word) return ret;

   wl = eina_hash_find(hash, lang);
   if(wl) {
      const Wiki_Lang_Magic_Word *mw = wl->magic_words;
      while(mw && mw->locale && ret == NULL) {
         if(strcmp(mw->locale, word) == 0)
            ret = mw->name;
         mw++;
      }
   }

   return ret;
}

const char *wiki_lang_message_get(Eina_Hash *hash, const char *lang, const char *name)
{
   const Wiki_Lang *wl = NULL;
   const char *ret = NULL;

   if(! hash) return ret;
   if(! lang) return ret;
   if(! name) return ret;

   wl = eina_hash_find(hash, lang);
   if(wl) {
      const Wiki_Lang_Message *lm = wl->messages;
      while(lm && lm->name && ret == NULL) {
         if(strcmp(lm->name, name) == 0)
            ret = lm->message;
         lm++;
      }
   }

   return ret;
}

Eina_Hash *wiki_languages_init(void)
{
   Eina_Hash *wiki_languages_hash = NULL;

   const Wiki_Lang *lang = wiki_languages;

   wiki_languages_hash = eina_hash_string_superfast_new(NULL);

   if(wiki_languages_hash) {
      while(lang->code) {
         eina_hash_add(wiki_languages_hash, lang->code, lang);
         lang++;
      }
   }

   return wiki_languages_hash;
}
